### ISSUE TITLE
[EPIC] As a developer I want to see high level overview of what p2p messages mina node sending and receiving, so I can figure out what node is doing and what is the sequence

### ISSUE THREAD

**Issue by vlad9486** [openmina/mina-network-debugger#7]
Parse and show in debugger type of messages. 

- [x] Meshsub messages types.
- [x] Kademlia messages types.
- [x] [Rpc](https://github.com/name-placeholder/mina-network-debugger/issues/8) types.
- [ ] [Ipfs related](https://github.com/name-placeholder/mina-network-debugger/issues/6): `/ipfs/id/1.0.0`, `/ipfs/id/push/1.0.0`, `/p2p/id/delta/1.0.0`.
- [ ] `/mina/peer-exchange`
- [ ] `/mina/bitswap-exchange`
- [ ] `/mina/node-status`
